### ISSUE TITLE
{'success': False, 'error': 'Your phone number was not provided in E.164 format, or free SMS are disabled for this country'}

### ISSUE THREAD

**Issue by rambo251006** [HACK3RY2J/Anon-SMS#21]
{'success': False, 'error': 'Your phone number was not provided in E.164 format, or free SMS are disabled for this country'}

**Comment by subha492** [comment]
same here. Do correct it.

**Comment by HACK3RY2J** [comment]
The country you are trying to send SMS is Blocked due to Overuse in recent times.
