### ISSUE TITLE
Error !! : Some dependencies are not installed

### ISSUE THREAD

**Issue by Jhongt796** [HACK3RY2J/Anon-SMS#23]
**When i run sudo bash Run.sh :**

Error !! : Some dependencies are not installed
Error Occured!!!
Use Non-Supported Version
Press Any Key To Use Non-supported Version
       
       
       
    **When Failed...:**
       
Checking For Updates...
Congratulation
Your Version is Up-To-Date

Starting Anon-SMS...

Notification : Anon-SMS Has Been OpenSourced !!!
              If you like the work Tip us Using Brave Browser.
              Join Telegram Discussion https://t.me/itzAnonSMS
              Due to overuse we are facing techinal Difficulties in sending SMS.
              It would be Restored Soon.

This Tool Is Used To Send Anonymous Messages
Enter The Details Of The Person You Want To Send Anonymous Message
        Enter Country Code (Without +) : 051
Enter Phone Number : +051 999999999
Enter Message to send : 519861686841351
Traceback (most recent call last):
  File "/home/thexerox/Anon-SMS/send.py", line 153, in <module>
    resp = requests.post('https://textbelt.com/text',{
NameError: name 'requests' is not defined

**Comment by HACK3RY2J** [comment]
A python Module name requests is missing.

Try Using Non-Supported Version.
