### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mishraji990** [HACK3RY2J/Anon-SMS#3]
![Screenshot_2020-03-26-00-22-23-657_com termux](https://user-images.githubusercontent.com/56390741/77574638-537f0700-6ef8-11ea-88b1-b56f5c7a0b15.jpg)
It's need to an update or else..
Kindly check that why it's not working
I have two version of this tool no one works

**Comment by HACK3RY2J** [comment]
We Are Very Sorry For All The Errors In Our Code..

All The Errors Have Been Fixed.
Now You Can Run The Tool Properly..
Please Check The Description For Running Tutorial...
