### ISSUE TITLE
![IMG_20200326_152555](https://user-images.githubusercontent.com/56390741/77633909-240edf80-6f76-11ea-9823-df0d47a961ad.jpg)

### ISSUE THREAD

**Issue by mishraji990** [HACK3RY2J/Anon-SMS#6]
![IMG_20200326_152555](https://user-images.githubusercontent.com/56390741/77633909-240edf80-6f76-11ea-9823-df0d47a961ad.jpg)

_Originally posted by @mishraji990 in https://github.com/HACK3RY2J/Anon-SMS/issues/5#issuecomment-604334949_

**Comment by HACK3RY2J** [comment]
The Service Has Been Temporarily Disabled By The Server.

It Should Restore Soon.
