### ISSUE TITLE
,

### ISSUE THREAD

**Issue by dynoh7** [HACK3RY2J/Anon-SMS#8]
![Screenshot_20210204-154139~2.png](https://user-images.githubusercontent.com/77390679/106894194-af611180-66ff-11eb-92c2-c27b2b3a3f95.png)

**Comment by HACK3RY2J** [comment]
This was due to because the server we were using for sending SMS has been
under maintainance for some time.

It's working fine now

**Comment by dynoh7** [comment]
Thanks 👌
