### ISSUE TITLE
Sms limit

### ISSUE THREAD

**Issue by vaibhav-rm** [HACK3RY2J/Anon-SMS#9]
Why is everyone limited to 1 spoof sms per day?
Atleast make it like 5 sms per or another way of getting more sms like watching ads or servey or something .LOL HOPE. I loved this let me know if there are more spoof sms applications on github.

**Comment by HACK3RY2J** [comment]
The API currently used in the tool allows you to use 1 SMS per day. You can
purchase their premium for more. But their premium is little costly.

We will add more stable free api in future updates.

**Comment by vaibhav-rm** [comment]
Ok thank you

**Comment by Dipraj2** [comment]
> Why is everyone limited to 1 spoof sms per day?
> Atleast make it like 5 sms per or another way of getting more sms like watching ads or servey or something .LOL HOPE. I loved this let me know if there are more spoof sms applications on github.

You can use vpn to get more messege daily :"3

**Comment by HACK3RY2J** [comment]
> > Why is everyone limited to 1 spoof sms per day?
> > Atleast make it like 5 sms per or another way of getting more sms like watching ads or servey or something .LOL HOPE. I loved this let me know if there are more spoof sms applications on github.
> 
> You can use vpn to get more messege daily :"3

But Cannot to Same number.
